name: CI
on: [push, pull_request]
jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.10' }
      - run: pip install -r requirements.txt
      - run: |
          test -f artifacts/preds/test_probs.npy || echo "Missing predictions (ok if not released yet)"
          test -f artifacts/preds/test_labels.npy || echo "Missing labels (ok if not released yet)"
